---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Rose-HTML-Objects
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  Clone::PP: 0
  DateTime: 0.20
  Email::Valid: 0
  Encode: 0
  File::Basename: 0
  File::Path: 0
  File::Spec: 0
  HTML::Entities: 0
  IO::String: 1.08
  Image::Size: 0
  Rose::DateTime: 0.532
  Rose::Object: 0.854
  Rose::URI: 0.021
  Scalar::Util: 0
  URI::Escape: 0
  perl: 5.006000
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Rose-HTML-Objects
  homepage: http://rose.googlecode.com/
  license: http://dev.perl.org/licenses/
  repository: http://rose.googlecode.com/svn/trunk/modules/Rose-HTML-Objects
  x_MailingList: http://groups.google.com/group/rose-html-objects
version: 0.614
