--- #YAML:1.0
name:                Rose-HTML-Objects
version:             0.550_05
abstract:            ~
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Carp:                          0
    Clone::PP:                     0
    Email::Valid:                  0
    HTML::Entities:                0
    Image::Size:                   0
    Rose::DateTime:                0.532
    Rose::Object:                  0.82
    Rose::URI:                     0.021
    Scalar::Defer:                 0
    Scalar::Util:                  0
    URI::Escape:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
