# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Rose-HTML-Objects
version:      0.024
version_from: lib/Rose/HTML/Objects.pm
installdirs:  site
requires:
    Email::Valid:                  0
    Image::Size:                   0
    Rose::DateTime:                0.0133
    Rose::Object:                  0.015
    Rose::URI:                     0.021
    Scalar::Util:                  0
    URI::Escape:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
