--- #YAML:1.0
name:               Rose-HTML-Objects
version:            0.555
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:            0
    Clone::PP:       0
    DateTime:        0.20
    Email::Valid:    0
    Encode:          0
    HTML::Entities:  0
    Image::Size:     0
    Rose::DateTime:  0.532
    Rose::Object:    0.85
    Rose::URI:       0.021
    Scalar::Util:    0
    URI::Escape:     0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.47_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
